### ISSUE TITLE
Cannot mount from HDD image made with HDD RawCopy

### ISSUE THREAD

**Issue by ghost** [aerosoul94/fatx-tools#4]
See attached log. 
[output.txt](https://github.com/aerosoul94/fatx-tools/files/3200378/output.txt)

**Comment by aerosoul94** [comment]
I think you may be using an older version of the GUI. It seems to have mounted SystemPartition and Partition1 just fine? Does it appear in the GUI? The other 3 partitions actually do not contain FATX file systems which is why it fails to mount those. I suppose that should be made clear through error logging. I also notice I left in a "Test" partition that shouldn't be there.

**Comment by ghost** [comment]
Ah, you're right, it does work in the GUI. Sorry about that! 

However, any data extracted (PNG/JPG/files) was corrupted. Not sure if it was just because I was using an image or if they were just naturally corrupted.

**Comment by aerosoul94** [comment]
HDDRawCopy produces a byte for byte copy of your hdd which is exactly what is needed. Are these files extracted from the main window or after performing analysis (right click a partition > Perform * Analysis)? Is there any data that doesn't appear to be corrupted? Does the same data show up ok on the Xbox 360?

**Comment by ghost** [comment]
Resolved in PM. Likely just file corruption on HDD, not the tool's fault.

**Comment by ghost** [comment]
Resolved in PM. Likely just file corruption on HDD, not the tool's fault.
